### ISSUE TITLE
Node & "ag" version compatibility issues and failure to produce code

### ISSUE THREAD

**Issue by gvensan** [asyncapi/java-spring-cloud-stream-template#253]
#### How to Reproduce
Tried potential permutation and combination of Node & "ag" (AsyncAPI code generator) versions

**Command executed:**

> ag -o ProcessPayment -p binder=solace -p artifactId=ProcessPayment -p groupId=org.taxi.nyc -p javaPackage=org.taxi.nyc -p host=taxi.messaging.solace.cloud:55555 -p username=public-taxi-user -p password=iliketaxis -p msgVpn=nyc-modern-taxi process_payment.yml @asyncapi/java-spring-cloud-stream-template

When using **_ag_** v1.9.0 or v1.8.6, **_node_** v14.16.1 it fails with exception:

```
Something went wrong:
Template render error: (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/resources/application.yml)
  TypeError: Cannot read property 'type' of null
    at Object._prettifyError (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:18:3)
    at Template.render (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:380:17)
    at /Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:703:12)
    at Generator.renderAndWriteToFile (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:617:27)
    at Generator.generateFile (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:667:5)
    at Generator.filesGenerationHandler (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:542:7)
    at Walker.<anonymous> (/Users/vengatagirivenkatesan/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:466:11)
```

When using **_ag_** v1.9.0 or v1.8.6, **_node_** v12.22.10 it fails with exception:

```
Something went wrong:
/Users/vengatagirivenkatesan/.nvm/versions/node/v12.22.10/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/filters/all.js:576
    const payload = pubOrSub.message()?.payload();
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Walker.<anonymous> (/Users/vengatagirivenkatesan/.nvm/versions/node/v12.22.10/lib/node_modules/@asyncapi/generator/lib/filtersRegistry.js:40:21)
    at Walker.emit (events.js:314:20)
    at Walker.EventEmitter.emit (domain.js:483:12)
```
#### Expected behavior
A clean, compilable and ready to [use](url) spring project :)

**Comment by gvensan** [comment]
[process_payment.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/8206350/process_payment.txt)

Attaching the YAML file for reference.

**Comment by CameronRushton** [comment]
I'm unable to reproduce this issue with the current version of the template (0.13.3). Please confirm if this is still an issue. Node 14+ is still a requirement in this version and this should be documented or fixed to be backwards compatible. There's another issue #274 that is only about node version so that shall be taken care of there.
I'll close this issue as fixed if it becomes stale again.

**Comment by gvensan** [comment]
Sure, please close it. Will reopen if needed.
