### ISSUE TITLE
Not able to generate application using the command

### ISSUE THREAD

**Issue by subhransu010683** [asyncapi/java-spring-cloud-stream-template#274]
#### Describe the bug
I have followed the steps and tried to generate application out of the yaml file. But its not getting generated. I am getting syntax error everytime with the yaml file mentioned in the example as well.

#### How to Reproduce
npm install -g @asyncapi/generator
ag https://bit.ly/asyncapi @asyncapi/java-spring-cloud-stream-template -o example

- Error Getting
AsyncAPI\Code> ag https://bit.ly/asyncapi @asyncapi/java-spring-cloud-stream-template -o example
(node:113144) ExperimentalWarning: The fs.promises API is experimental
Something went wrong:
C:\nvm\v10.15.3\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-cloud-stream-template\filters\all.js:576
    const payload = pubOrSub.message()?.payload();
                                       ^

SyntaxError: Unexpected token .
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Walker.walker.on (C:\nvm\v10.15.3\node_modules\@asyncapi\generator\lib\filtersRegistry.js:40:21)
    at Walker.emit (events.js:189:13)
    at Walker.EventEmitter.emit (domain.js:441:20)
    at Object.emitSingleEvents [as emitNodeType] (C:\nvm\v10.15.3\node_modules\@asyncapi\generator\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\nvm\v10.15.3\node_modules\@asyncapi\generator\node_modules\walk\lib\walk.js:88:19)
    at C:\nvm\v10.15.3\node_modules\@asyncapi\generator\node_modules\walk\lib\walk.js:106:12

#### Expected behavior
Project should created

**Comment by CameronRushton** [comment]
@subhransu010683 What version of node are you using? I wasn't able to reproduce the issue with node version 14.19. It looks like optional chaining is the issue which was introduced in node 14.0.
