### ISSUE TITLE
Template doesn't like "array" type in schema

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#316]
#### Describe the bug
When using this code generator template it was spitting out an unclear error with the attached file [asyncapi.zip](https://github.com/asyncapi/java-spring-cloud-stream-template/files/10396212/asyncapi.zip). However once you remove the `products` part of the schema it works successfully. Since the provided asyncapi file is valid I assume this template does not properly handle schemas that use an object with the `array` type at this level. 
```
 /tmp  ag -o TEST asyncapi.json https://github.com/asyncapi/java-spring-cloud-stream-template.git                                                                                                                                      1 ✘
Something went wrong:
Template render error: (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/java/$$everySchema$$.java)
  Template render error: (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/partials/java-package) [Line 5, Column 49]
  TypeError: prop.items(...).type is not a function
    at Object._prettifyError (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at eval (eval at _compile (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:19:11)
    at /Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:571:11
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:50:3)
    at Template.render (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at eval (eval at _compile (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:18:10)
    at fn (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:26:24)
    at /Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:66:22
    at executeSync (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:8:15)
    at /Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:65:11
    at eval (eval at _compile (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:14:1)
    at Environment.getTemplate (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:279:9)
    at eval (eval at _compile (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:12:5)
    at fn (/Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:26:24)
    at /Users/Mdipasquale/.nvm/versions/node/v18.7.0/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:66:22
```

#### How to Reproduce
Download attached [asyncapi.zip](https://github.com/asyncapi/java-spring-cloud-stream-template/files/10396212/asyncapi.zip) file. 
Run `ag -o TEST asyncapi.json https://github.com/asyncapi/java-spring-cloud-stream-template.git` 

#### Expected behavior
A successful project should be generated

**Comment by CameronRushton** [comment]
@Mrc0113 I think the asyncapi doc provided is the one that is successful, yeah? The one with `products` removed.

**Comment by Mrc0113** [comment]
Sorry @CameronRushton, I think this is the right file
[asyncapiWithProducts.json.zip](https://github.com/asyncapi/java-spring-cloud-stream-template/files/10572350/asyncapiWithProducts.json.zip)
