### ISSUE TITLE
Can't determine the type of property

### ISSUE THREAD

**Issue by marian-varga** [asyncapi/java-spring-cloud-stream-template#356]
### Describe the bug.

Cannot generate code from the spec

Something went wrong:
Template render error: (node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-cloud-stream-template\template\src\main\java\$$everySchema$$.java) [Line 10, Column 51]
  Error: Can't determine the type of property petType
    at eval (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:46:11)
    at node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:510:9
    at eval (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:12:11)
    at node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:510:9
    at Template.root [as rootRenderFunc] (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:367:3)
    at Template.getExported (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:508:10)
    at eval (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:11:5)
    at Environment.getTemplate (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:225:9)
    at Template.root [as rootRenderFunc] (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:9:5)

### Expected behavior

Code should be generated

### Screenshots

![image](https://github.com/asyncapi/java-spring-cloud-stream-template/assets/70155732/3cf3e829-a386-46c7-9c56-86bfe1996242)

### How to Reproduce

ag ../polymorphism.yaml @asyncapi/java-spring-cloud-stream-template

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by marian-varga** [comment]
```yaml
asyncapi: 2.6.0
info:
  title: Example of schema using polymorphism
  version: 2.6.0
channels:
  pet:
    subscribe:
      message:
        payload:
          type: object
          properties:
            pet:
              $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      discriminator: petType
      properties:
        name:
          type: string
        petType:
          type: string
      required:
        - name
        - petType
    ## applies to instances with `petType: "Cat"`
    ## because that is the schema name
    Cat:
      description: A representation of a cat
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            huntingSkill:
              type: string
              description: The measured skill for hunting
              enum:
                - clueless
                - lazy
                - adventurous
                - aggressive
          required:
            - huntingSkill
    ## applies to instances with `petType: "Dog"`
    ## because that is the schema name
    Dog:
      description: A representation of a dog
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            packSize:
              type: integer
              format: int32
              description: the size of the pack the dog is from
              minimum: 0
          required:
            - packSize
    ## applies to instances with `petType: "StickBug"`
    ## because that is the required value of the discriminator field,
    ## overriding the schema name
    StickInsect:
      description: A representation of an Australian walking stick
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            petType:
              const: StickBug
            color:
              type: string
          required:
            - color
```

**Comment by CameronRushton** [comment]
Thanks for the issue. The correct fix for this problem is to start supporting the discriminator which would handle this case as part of the implementation. Since there appears to be low adoption of this property in other templates and due to the complexity, it's not something that is expected to be implemented immediately. I think opening another issue for this would be the best thing to do.
For this bug, it may be minimally sufficient to at least generate _something_ in this case without handling the discriminator. I suspect it's possible to reproduce this issue independently of any discriminator by having a property that is a const (of type string or int) without a type explicitly defined. This can be fixed in the template.
Another fix is to define the type in the schema, but that should be optional which right now, clearly isn't if we want the code to generate.

Please let us know if this is still an issue and what solution is acceptable.

**Comment by marian-varga** [comment]
I solved it by using OpenAPI schema instead of AsyncAPI schema and using the OpenAPI generator that handles the discriminators without issues.
