### ISSUE TITLE
Error: filter not found: upperFirst

### ISSUE THREAD

**Issue by LeandroBastos-acn** [asyncapi/java-spring-cloud-stream-template#42]
OS: Windows 10
Generator: 0.53.1 (Docker run)

Command to reproduce:
docker run --rm -it -v ${PWD}/test/docs/streetlights.yml:/app/asyncapi.yml -v ${PWD}/output:/app/output asyncapi/generator -o ./output asyncapi.yml @asyncapi/java-spring-cloud-stream-template --force-write

Result:
Something went wrong:
Template render error: (/app/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/java/$$schema$$.java)
  Error: filter not found: upperFirst
    at Object._prettifyError (/app/node_modules/nunjucks/src/lib.js:36:11)
    at /app/node_modules/nunjucks/src/environment.js:561:19
    at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:44:11)
    at /app/node_modules/nunjucks/src/environment.js:611:9
    at Template.root [as rootRenderFunc] (eval at _compile (/app/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:830:3)
    at Template.getExported (/app/node_modules/nunjucks/src/environment.js:609:10)
    at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:43:5)
    at createTemplate (/app/node_modules/nunjucks/src/environment.js:313:9)
    at handle (/app/node_modules/nunjucks/src/environment.js:325:11)
    at /app/node_modules/nunjucks/src/environment.js:337:9
    at next (/app/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/app/node_modules/nunjucks/src/lib.js:286:3)
    at Environment.getTemplate (/app/node_modules/nunjucks/src/environment.js:319:9)
    at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:41:5)
    at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:23:1)
    at fn (/app/node_modules/a-sync-waterfall/index.js:26:24)

**Comment by damaru-inc** [comment]
Sorry, but I can't reproduce the error. I do get a different error because currently this template does not work with the streetlights example file, it expects descriptions of the payload to be under components/schemas.
