### ISSUE TITLE
Template render error: topicInfo filter: type not found in typeMap: [object Object]

### ISSUE THREAD

**Issue by anmaso** [asyncapi/java-spring-cloud-stream-template#87]
#### Describe the bug
Generator gives an error

```
/app # vi /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-strea
m-template/filters/all.js 
 /app # ag -o /app/output2 /app/streetlights.yaml @asyncapi/java-spring-cloud-stream-template --force-write -p javaPackage=com.example.foo -p groupId=com.example -p artifactId=ExampleArtifactId
 Something went wrong:
 Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/java/Messaging.java)
   Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/partials/java-package)
  Error: topicInfo filter: type not found in typeMap: [object Object]
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:561:19
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:19:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:569:11
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:31:3)
    at Template.render (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:550:10)
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:18:10)
    at fn (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:26:24)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:66:22
    at executeSync (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:8:15)
```

#### How to Reproduce
Downloaded the streetlights.yaml example contract from: https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/streetlights.yml

Using the Docker CLI command to generate the java code
```
docker run --rm -it \
-v ${PWD}/streetlights.yml:/app/asyncapi.yml \
-v ${PWD}/output:/app/output \
asyncapi/generator -o /app/output /app/asyncapi.yml @asyncapi/java-spring-cloud-stream-template --force-write
```

#### Expected behavior
The way to correct the behaviour was to change the file filters/all.js (haven't reviewed it in detail)
from:
`const javaType = typeMap.get(type);`

to this one:
`const javaType = type.javaType || typeMap.get(type);`

**Comment by derberg** [comment]
@anmaso thanks for the issue. Could you open up a PR with the fix?
